cluster dashboard + docs
smartcontractkit/wasp pull request #19
Opened 2023-05-07 23:03 UTC by skudasov

2023-05-08 10:42 UTC, sebawo commented on CLUSTER.md
> +How it works:
@skudasov i would like to see here `Motivation` or `Context` section where we're explaining why we even want to need to use this feature.

2023-05-08 14:58 UTC, tateexon requested changes

2023-05-08 14:58 UTC, tateexon commented on examples/cluster/cluster_test.go
> +			"image":                     "f4hrenh9it/wasp_test:latest",
Another spot to change to a chainlink ecr.

2023-05-08 14:58 UTC, tateexon commented on CLUSTER.md
> +ChartPath: "oci://registry-1.docker.io/f4hrenh9it/wasp:v0.1.7"
And another.

2023-05-08 14:58 UTC, tateexon commented on CLUSTER.md
> +			"image":              "f4hrenh9it/wasp_test:latest",
And another.

2023-05-09 09:49 UTC, sebawo approved these changes

2023-05-09 13:26 UTC, tateexon approved these changes

2023-05-09 13:50 UTC, merged